[package]
name = "jieba-rs"
version.workspace = true

categories = ["text-processing"]
description = "Jieba Chinese Word Segmentation in Rust"
keywords = ["nlp", "chinese", "segmentation"]

edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["default-dict"]
default-dict = ["dep:include-flate"]
tfidf = ["dep:ordered-float", "dep:include-flate"]
textrank = ["dep:ordered-float"]
ts-rs = ["dep:ts-rs"]

[dependencies]
jieba-macros = { workspace = true }
bytecount = { workspace = true }
rustc-hash = { workspace = true }
include-flate = { workspace = true, optional = true }
ordered-float = { workspace = true, optional = true }
ts-rs = { version = "12.0.1", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = { version = "0.2.126" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
codspeed-criterion-compat = { workspace = true }
expect-test = { workspace = true }
rayon = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
tikv-jemallocator = "0.7.0"

[target.'cfg(target_family = "wasm")'.dev-dependencies]
wasm-bindgen-test = { version = "0.3.50" }

[[bench]]
name = "jieba_benchmark"
harness = false
required-features = ["tfidf", "textrank"]
